=== geoffroy-noel-ddh/crossreads/tools/schemas/dts_collection_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "DTS_COLLECTION",
  "type": "object",
  "properties": {
    "@context": {
      "type": "object",
      "properties": {
        "@vocab": {
          "type": "string"
        },
        "dc": {
          "type": "string"
        },
        "dts": {
          "type": "string"
        }
      }
    },
    "@id": {
      "type": "string"
    },
    "@type": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "dts:dublincore": {
      "type": "object",
      "properties": {
        "dc:type": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "dc:creator": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "@language": {
                "type": "string"
              },
              "@value": {
                "type": "string"
              }
            }
          }
        },
        "dc:language": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "dc:title": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "@language": {
                "type": "string"
              },
              "@value": {
                "type": "string"
              }
            }
          }
        },
        "dc:description": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "@language": {
                "type": "string"
              },
              "@value": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "totalItems": {
      "type": "number"
    },
    "dts:totalParents": {
      "type": "number"
    },
    "dts:totalChildren": {
      "type": "number"
    },
    "member": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "@id": {
            "type": "string"
          },
          "@type": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "totalItems": {
            "type": "number"
          },
          "dts:totalParents": {
            "type": "number"
          },
          "dts:totalChildren": {
            "type": "number"
          },
          "dts:dublincore": {
            "type": "object",
            "properties": {
              "dc:title": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "@language": {
                      "type": "string"
                    },
                    "@value": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "@language",
                    "@value"
                  ]
                }
              },
              "dc:description": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "@language": {
                      "type": "string"
                    },
                    "@value": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "@language",
                    "@value"
                  ]
                }
              },
              "dc:type": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "dc:creator": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "@language": {
                      "type": "string"
                    },
                    "@value": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "@language",
                    "@value"
                  ]
                }
              },
              "dc:contributor": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "dc:language": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          },
          "dts:download": {
            "type": "string"
          },
          "dts:citeDepth": {
            "type": "number"
          },
          "dts:citeStructure": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "dts:citeType": {
                  "type": "string"
                },
                "dts:citeStructure": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "dts:citeType": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "dts:citeType"
                    ]
                  }
                }
              },
              "required": [
                "dts:citeType",
                "dts:citeStructure"
              ]
            }
          }
        },
        "required": [
          "@id",
          "@type",
          "title",
          "description",
          "totalItems",
          "dts:totalParents",
          "dts:totalChildren",
          "dts:dublincore",
          "dts:download",
          "dts:citeDepth",
          "dts:citeStructure"
        ]
      }
    }
  }
}

=== geoffroy-noel-ddh/crossreads/app/data/2023-01/collection.json
{
    "@context": {
      "@vocab": "https://www.w3.org/ns/hydra/core#",
      "dc": "http://purl.org/dc/terms/",
      "dts": "https://w3id.org/dts/api#"
    },
    "@id": "http://http://sicily.classics.ox.ac.uk",
    "@type": "Collection",
    "title": "I.Sicily",
    "dts:dublincore": {
      "dc:type": [
        "http://purl.org/dc/dcmitype/Collection"
      ],
      "dc:creator": [
        {
          "@language": "en",
          "@value": "Various"
        }
      ],
      "dc:language": [
        "en"
      ],
      "dc:title": [
        {
          "@language": "en",
          "@value": "I.Sicily"
        }
      ],
      "dc:description": [
        {
          "@language": "en",
          "@value": "A digital corpus of Sicilian inscriptions"
        }
      ]
    },
    "totalItems": 4128,
    "dts:totalParents": 0,
    "dts:totalChildren": 4128,
    "member": [
      {
        "@id": "http://sicily.classics.ox.ac.uk/inscription/ISic000001",
        "@type": "Resource",
        "title": "ISic000001",
        "description": "Funerary inscription of Zethus",
        "totalItems": 0,
        "dts:totalParents": 1,
        "dts:totalChildren": 0,
        "dts:dublincore": {
          "dc:title": [
            {
              "@language": "en",
              "@value": "ISic000001"
            }
          ],
          "dc:description": [
            {
              "@language": "en",
              "@value": "Funerary inscription of Zethus"
            }
          ],
          "dc:type": [
            "dc:Text"
          ],
          "dc:creator": [
            {
              "@language": "en",
              "@value": "I.Sicily Contributors"
            }
          ],
          "dc:contributor": [
            "I.Sicily Contributors"
          ],
          "dc:language": [
            "en"
          ]
        },
        "dts:passage": "/api/dts/documents?id=ISic000001",
        "//dts:download": "https://raw.githubusercontent.com/ISicily/ISicily/master/inscriptions/ISic000001.xml",
        "dts:download": "data/2023-01/ISic000001.xml",
        "dts:citeDepth": 2,
        "dts:citeStructure": [
          {
            "dts:citeType": "inscription",
            "dts:citeStructure": [
              {
                "dts:citeType": "line"
              }
            ]
          }
        ]
      },
      {
        "@id": "http://sicily.classics.ox.ac.uk/inscription/ISic000007",
        "@type": "Resource",
        "title": "ISic000007",
        "description": "Construction of fortification works under Sextus Pompeius by L. Plinius Rufus",
        "totalItems": 0,
        "dts:totalParents": 1,
        "dts:totalChildren": 0,
        "dts:dublincore": {
          "dc:title": [
            {
              "@language": "en",
              "@value": "ISic000007"
            }
          ],
          "dc:description": [
            {
              "@language": "en",
              "@value": "Construction of fortification works under Sextus Pompeius by L. Plinius Rufus"
            }
          ],
          "dc:type": [
            "dc:Text"
          ],
          "dc:creator": [
            {
              "@language": "en",
              "@value": "I.Sicily Contributors"
            }
          ],
          "dc:contributor": [
            "I.Sicily Contributors"
          ],
          "dc:language": [
            "en"
          ]
        },
        "dts:passage": "/api/dts/documents?id=ISic000007",
        "//dts:download": "https://raw.githubusercontent.com/ISicily/ISicily/master/inscriptions/ISic000007.xml",
        "dts:download": "data/2023-01/ISic000007.xml",
        "dts:citeDepth": 2,
        "dts:citeStructure": [
          {
            "dts:citeType": "inscription",
            "dts:citeStructure": [
              {
                "dts:citeType": "line"
              }
            ]
          }
        ]
      },
      {
        "@id": "http://sicily.classics.ox.ac.uk/inscription/ISic000031",
        "@type": "Resource",
        "title": "ISic000031",
        "description": "I.Sicily inscription 000031",
        "totalItems": 0,
        "dts:totalParents": 1,
        "dts:totalChildren": 0,
        "dts:dublincore": {
          "dc:title": [
            {
              "@language": "en",
              "@value": "ISic000031"
            }
          ],
          "dc:description": [
            {
              "@language": "en",
              "@value": "I.Sicily inscription 000031"
            }
          ],
          "dc:type": [
            "dc:Text"
          ],
          "dc:creator": [
            {
              "@language": "en",
              "@value": "I.Sicily Contributors"
            }
          ],
          "dc:contributor": [
            "I.Sicily Contributors"
          ],
          "dc:language": [
            "en"
          ]
        },
        "dts:passage": "/api/dts/documents?id=ISic000031",
        "//dts:download": "https://raw.githubusercontent.com/ISicily/ISicily/master/inscriptions/ISic000031.xml",
        "dts:download": "data/2023-01/ISic000031.xml",
        "dts:citeDepth": 2,
        "dts:citeStructure": [
          {
            "dts:citeType": "inscription",
            "dts:citeStructure": [
              {
                "dts:citeType": "line"
              }
            ]
          }
        ]
      },
      {
        "@id": "http://sicily.classics.ox.ac.uk/inscription/ISic000046",
        "@type": "Resource",
        "title": "ISic000046",
        "description": "I.Sicily inscription 000046",
        "totalItems": 0,
        "dts:totalParents": 1,
        "dts:totalChildren": 0,
        "dts:dublincore": {
          "dc:title": [
            {
              "@language": "en",
              "@value": "ISic000046"
            }
          ],
          "dc:description": [
            {
              "@language": "en",
              "@value": "I.Sicily inscription 000046"
            }
          ],
          "dc:type": [
            "dc:Text"
          ],
          "dc:creator": [
            {
              "@language": "en",
              "@value": "I.Sicily Contributors"
            }
          ],
          "dc:contributor": [
            "I.Sicily Contributors"
          ],
          "dc:language": [
            "en"
          ]
        },
        "dts:passage": "/api/dts/documents?id=ISic000046",
        "//dts:download": "https://raw.githubusercontent.com/ISicily/ISicily/master/inscriptions/ISic000046.xml",
        "dts:download": "data/2023-01/ISic000046.xml",
        "dts:citeDepth": 2,
        "dts:citeStructure": [
          {
            "dts:citeType": "inscription",
            "dts:citeStructure": [
              {
                "dts:citeType": "line"
              }
            ]
          }
        ]
      },
      {
        "@id": "http://sicily.classics.ox.ac.uk/inscription/ISic000079",
        "@type": "Resource",
        "title": "ISic000079",
        "description": "Epitaph of Crispia Salvia",
        "totalItems": 0,
        "dts:totalParents": 1,
        "dts:totalChildren": 0,
        "dts:dublincore": {
          "dc:title": [
            {
              "@language": "en",
              "@value": "ISic000079"
            }
          ],
          "dc:description": [
            {
              "@language": "en",
              "@value": "Epitaph of Crispia Salvia"
            }
          ],
          "dc:type": [
            "dc:Text"
          ],
          "dc:creator": [
            {
              "@language": "en",
              "@value": "I.Sicily Contributors"
            }
          ],
          "dc:contributor": [
            "I.Sicily Contributors"
          ],
          "dc:language": [
            "en"
          ]
        },
        "dts:passage": "/api/dts/documents?id=ISic000079",
        "//dts:download": "https://raw.githubusercontent.com/ISicily/ISicily/master/inscriptions/ISic000079.xml",
        "dts:download": "data/2023-01/ISic000079.xml",
        "dts:citeDepth": 2,
        "dts:citeStructure": [
          {
            "dts:citeType": "inscription",
            "dts:citeStructure": [
              {
                "dts:citeType": "line"
              }
            ]
          }
        ]
      },
      {
        "@id": "http://sicily.classics.ox.ac.uk/inscription/ISic002745",
        "@type": "Resource",
        "title": "ISic002745",
        "description": "Fragments of a monumental Greek inscription",
        "totalItems": 0,
        "dts:totalParents": 1,
        "dts:totalChildren": 0,
        "dts:dublincore": {
          "dc:title": [{ "@language": "en", "@value": "ISic002745" }],
          "dc:description": [
            {
              "@language": "en",
              "@value": "Fragments of a monumental Greek inscription"
            }
          ],
          "dc:type": ["dc:Text"],
          "dc:creator": [
            { "@language": "en", "@value": "I.Sicily Contributors" }
          ],
          "dc:contributor": ["I.Sicily Contributors"],
          "dc:language": ["en"]
        },
        "dts:passage": "/api/dts/documents?id=ISic002745",
        "//dts:download": "https://raw.githubusercontent.com/ISicily/ISicily/master/inscriptions/ISic002745.xml",
        "dts:download": "data/2023-01/ISic002745.xml",
        "dts:citeDepth": 2,
        "dts:citeStructure": [
          {
            "dts:citeType": "inscription",
            "dts:citeStructure": [{ "dts:citeType": "line" }]
          }
        ]
      }  
    ]
  }
